export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const HOME_POSTS_START = 'HOME_POSTS_START'
export const HOME_POSTS_SUCCESS = 'HOME_POSTS_SUCCESS'
export const HOME_POSTS_FAIL = 'HOME_POSTS_FAIL'
export const HOME_POSTS_LOAD_MORE_START = 'HOME_POSTS_LOAD_MORE_START'
export const HOME_POSTS_LOAD_MORE_SUCCESS = 'HOME_POSTS_LOAD_MORE_SUCCESS'

export const PROFILE_POSTS_START = 'PROFILE_POSTS_START'
export const PROFILE_POSTS_SUCCESS = 'PROFILE_POSTS_SUCCESS'
export const PROFILE_POSTS_FAIL = 'PROFILE_POSTS_FAIL'
export const PROFILE_POSTS_LOAD_MORE_START = 'PROFILE_POSTS_LOAD_MORE_START'
export const PROFILE_POSTS_LOAD_MORE_SUCCESS = 'PROFILE_POSTS_LOAD_MORE_SUCCESS'

export const USER_PROFILE_START = 'USER_PROFILE_START'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const PENDING_FOLLOWS_START = 'PENDING_FOLLOWS_START'
export const PENDING_FOLLOWS_SUCCESS = 'PENDING_FOLLOWS_SUCCESS'
export const PENDING_FOLLOWS_FAIL = 'PENDING_FOLLOWS_FAIL'