name: Build Android adhoc

on:
  push:
    branches:
      - master

jobs:
  build-android-adhoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          package: "jdk"

      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli

      - name: Install yarn dependencies
        run: |
          yarn install

      - name: Build android
        run: yarn androidDebug --scan

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: android/app/build/outputs/apk/release/app-release.apk
